name: edu_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  agora_rtc_engine: ^4.0.2
  audioplayers: ^0.16.0
  charts_flutter: ^0.10.0
  cloud_firestore: ^2.4.0
  datetime_picker_formfield: ^2.0.0
  firebase_auth: ^3.0.1
  firebase_core: ^1.4.0
  flutter_bloc: ^7.0.1
  flutter_sparkline: ^0.1.0
  flutter_unity_widget: ^4.2.1
  image_picker: ^0.8.0+3
  mailer: ^5.0.0
  permission_handler: ^8.1.1
  video_player: ^1.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/users.png
    - assets/images/admin.png
    - assets/images/pocetna.png
    - assets/images/mental_illness.png
    - assets/images/down.png
    - assets/images/autism.png
    - assets/images/a1.png
    - assets/images/a2.png
    - assets/images/cetkica.png
    - assets/images/pranje_zuba.png
    - assets/images/oblacenje.jpg
    - assets/images/majica.png
    - assets/images/obuvanje.png
    - assets/images/cipele.png
    - assets/images/jede.png
    - assets/images/hrana.png
    - assets/images/sapun.png
    - assets/images/pranje_ruku.png
    - assets/images/rukovanje.png
    - assets/images/ruka.png
    - assets/images/brojevi.png
    - assets/images/zivotinje.png
    - assets/images/slovo.png
    - assets/images/oblici.png
    - assets/images/voceipovrce.png
    - assets/images/reci.png
    - assets/images/boje.png
    - assets/images/moods.png
    - assets/images/goddoba.png
    - assets/images/videi.png
    - assets/images/spongebob.png
    - assets/images/match.png
    - assets/images/count.png
    - assets/images/miss.png
    - assets/images/play.png
    - assets/images/background.jpg
    - assets/images/numbers/0.png
    - assets/images/numbers/1.png
    - assets/images/numbers/2.png
    - assets/images/numbers/3.png
    - assets/images/numbers/4.png
    - assets/images/numbers/5.png
    - assets/images/numbers/6.png
    - assets/images/numbers/7.png
    - assets/images/numbers/8.png
    - assets/images/numbers/9.png
    - assets/images/separate.png
    - assets/images/question.png
    - assets/images/tacno.png
    - assets/images/lopte.png
    - assets/images/jabuke.png
    - assets/images/kola.png
    - assets/images/fruits/apple.png
    - assets/images/fruits/banana.png
    - assets/images/fruits/jagoda.png
    - assets/images/fruits/kivi.png
    - assets/images/fruits/kruska.png
    - assets/images/fruits/kupina.png
    - assets/images/fruits/malina.png
    - assets/images/fruits/limun.png
    - assets/images/fruits/tresnja.png
    - assets/images/fruits/sarg.png
    - assets/images/fruits/brokoli.png
    - assets/images/fruits/kukuruz.png
    - assets/images/objects/auto.png
    - assets/images/objects/avion.png
    - assets/images/objects/lopta.png
    - assets/images/objects/majmun.png
    - assets/images/objects/meda.png
    - assets/images/objects/oblak.png
    - assets/images/objects/patike.png
    - assets/images/objects/sunce.png
    - assets/images/objects/traktor.png
    - assets/images/nauci.png
    - assets/images/animals/kamila.png
    - assets/images/animals/kokoska.png
    - assets/images/animals/krava.png
    - assets/images/animals/lav.png
    - assets/images/animals/macka.png
    - assets/images/animals/medved.png
    - assets/images/animals/pas.png
    - assets/images/animals/slon.png
    - assets/images/animals/zaba.png
    - assets/images/animals/zirafa.png
    - assets/images/moods/gadjenje.png
    - assets/images/moods/iznenadjen.png
    - assets/images/moods/ljut.png
    - assets/images/moods/plac.png
    - assets/images/moods/smeh.png
    - assets/images/moods/uplasen.png
    - assets/images/seasons/kisobran.png
    - assets/images/seasons/bickil.png
    - assets/images/seasons/bazen.png
    - assets/images/seasons/skola.png
    - assets/images/seasons/sneg.png
    - assets/images/seasons/zima.png
    - assets/images/seasons/jesen.png
    - assets/images/seasons/leto.png
    - assets/images/geometry/krug.png
    - assets/images/geometry/polukrug.png
    - assets/images/geometry/kvadrat.png
    - assets/images/geometry/mesec.png
    - assets/images/geometry/munja.png
    - assets/images/geometry/oktagon.png
    - assets/images/geometry/strela.png
    - assets/images/geometry/trougao.png
    - assets/images/geometry/zvezda.png
    - assets/images/senzorna.jpg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
